-- 表 config 的结构
CREATE TABLE IF NOT EXISTS [config] (
    id INTEGER NOT NULL PRIMARY KEY,
    data JSON NOT NULL,
    version INTEGER NOT NULL,
    created_at DATETIME NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
    updated_at DATETIME DEFAULT 'CURRENT_TIMESTAMP'
);