"""fix progress and retry_count fields not nullable

Revision ID: af6b4f6e66b8
Revises: hsai_005_add_collaborators_to_tasks
Create Date: 2025-09-18 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'af6b4f6e66b8'
down_revision = 'hsai_005_add_collaborators_to_tasks'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hsai_tasks', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.BigInteger(),
               nullable=False)
        batch_op.alter_column('retry_count',
               existing_type=sa.BigInteger(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hsai_tasks', schema=None) as batch_op:
        batch_op.alter_column('retry_count',
               existing_type=sa.BigInteger(),
               nullable=True)
        batch_op.alter_column('progress',
               existing_type=sa.BigInteger(),
               nullable=True)

    # ### end Alembic commands ###